volumes:
  postgres_data:
  front-end-node_modules:
  back-end-node_modules:

services:
  postgres:
    image: postgres:12.4
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: mobile-club
      POSTGRES_PASSWORD: mobile-club
      POSTGRES_DB: url-shortener
    volumes:
      - postgres_data:/var/lib/postgresql/data

  front-end:
    build: './front-end/'
    restart: unless-stopped
    volumes:
      - './front-end:/app'
      - 'front-end-node_modules:/app/node_modules'
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true

  back-end:
    build: './back-end/'
    restart: unless-stopped
    volumes:
      - './back-end:/app'
      - 'back-end-node_modules:/app/node_modules'
    ports:
      - "4000:4000"
    depends_on:
      - postgres
